# Generated by Django 4.2.11 on 2024-10-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("melon_uid", models.CharField(max_length=20, unique=True)),
                ("rank", models.PositiveSmallIntegerField()),
                ("album_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=100)),
                ("cover_url", models.URLField()),
                ("lyrics", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("like_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "songs",
                    models.ManyToManyField(
                        related_name="music_playlist_songs", to="music.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
