# Generated by Django 4.2.11 on 2024-10-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("melon_uid", models.CharField(max_length=20)),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                ("album_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=100)),
                ("cover_url", models.URLField()),
                ("lyrics", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("release_date", models.DateField(default=django.utils.timezone.now)),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "song_file",
                    models.FileField(blank=True, null=True, upload_to="songs/"),
                ),
                (
                    "like_count",
                    models.ManyToManyField(
                        blank=True,
                        related_name="like_count",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
