# Generated by Django 4.2.11 on 2024-10-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Music",
        ),
    ]
